# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C6bG3DDaT-1_1y25iCRrt_DjiYNa5zAk
"""

import os
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.metrics import classification_report, confusion_matrix, precision_score, recall_score, f1_score
import matplotlib.pyplot as plt
import random

data_dir = "BRAIN IMAGE DATA"

img_size = 64
depth = 32
batch_size = 4
epochs = 100

class_names = ["EMCI", "LMCI", "NC"]

def load_data(folder):
    data = []
    labels = []
    for label, cname in enumerate(class_names):
        cpath = os.path.join(folder, cname)
        for file in os.listdir(cpath):
            fpath = os.path.join(cpath, file)
            img = tf.keras.preprocessing.image.load_img(fpath, target_size=(img_size, img_size))
            img = tf.keras.preprocessing.image.img_to_array(img)
            img = img / 255.0
            volume = np.stack([img[:,:,0]] * depth, axis=-1)
            volume = np.expand_dims(volume, axis=-1)
            data.append(volume)
            labels.append(label)
    return np.array(data), np.array(labels)

x_train, y_train = load_data(os.path.join(data_dir, "train"))
x_val, y_val = load_data(os.path.join(data_dir, "val"))
x_test, y_test = load_data(os.path.join(data_dir, "test"))

y_train = tf.keras.utils.to_categorical(y_train, 3)
y_val = tf.keras.utils.to_categorical(y_val, 3)
y_test = tf.keras.utils.to_categorical(y_test, 3)

def augment(volume):
    if random.random() > 0.5:
        volume = np.flip(volume, axis=1)
    if random.random() > 0.5:
        volume = np.flip(volume, axis=2)
    return volume

x_train_aug = np.array([augment(v) for v in x_train])

model = models.Sequential([
    layers.Conv3D(32, (3,3,3), activation='relu', input_shape=(img_size, img_size, depth, 1)),
    layers.MaxPooling3D((2,2,2)),
    layers.BatchNormalization(),

    layers.Conv3D(64, (3,3,3), activation='relu'),
    layers.MaxPooling3D((2,2,2)),
    layers.BatchNormalization(),

    layers.Conv3D(128, (3,3,3), activation='relu'),
    layers.MaxPooling3D((2,2,2)),
    layers.BatchNormalization(),

    layers.Conv3D(256, (3,3,3), activation='relu'),
    layers.MaxPooling3D((2,2,2)),
    layers.BatchNormalization(),

    layers.Flatten(),
    layers.Dense(512, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(3, activation='softmax')
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(
    x_train_aug, y_train,
    validation_data=(x_val, y_val),
    epochs=epochs,
    batch_size=batch_size
)

test_loss, test_acc = model.evaluate(x_test, y_test)

y_pred = model.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

precision = precision_score(y_true, y_pred_classes, average='weighted')
recall = recall_score(y_true, y_pred_classes, average='weighted')
f1 = f1_score(y_true, y_pred_classes, average='weighted')

print("Accuracy:", test_acc)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

print(classification_report(y_true, y_pred_classes, target_names=class_names))

cm = confusion_matrix(y_true, y_pred_classes)
print(cm)

plt.figure()
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(['Train', 'Validation'])
plt.show()

plt.figure()
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend(['Train', 'Validation'])
plt.show()

model.save("brain_advanced_3d_model.h5")

loaded_model = tf.keras.models.load_model("brain_advanced_3d_model.h5")

def predict_single(path):
    img = tf.keras.preprocessing.image.load_img(path, target_size=(img_size, img_size))
    img = tf.keras.preprocessing.image.img_to_array(img)/255.0
    volume = np.stack([img[:,:,0]] * depth, axis=-1)
    volume = np.expand_dims(volume, axis=(0,-1))
    pred = loaded_model.predict(volume)
    return class_names[np.argmax(pred)], np.max(pred)

test_folder = os.path.join(data_dir, "test")

results = []

for cname in class_names:
    cpath = os.path.join(test_folder, cname)
    files = os.listdir(cpath)
    for f in files[:10]:
        fpath = os.path.join(cpath, f)
        label, conf = predict_single(fpath)
        results.append((f, label, conf))

for r in results:
    print(r)

counts = [0,0,0]
for r in results:
    counts[class_names.index(r[1])] += 1

plt.figure()
plt.bar(class_names, counts)
plt.xlabel("Class")
plt.ylabel("Count")
plt.show()